services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: nakama
      POSTGRES_PASSWORD: localdb
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 10
    network_mode: "host"
    restart: unless-stopped

  nakama:
    image: registry.heroiclabs.com/heroiclabs/nakama:3.30.0
    # Postgres тоже сидит на host-сети, так что подключаемся по 127.0.0.1
    entrypoint: >
      /bin/sh -ecx "
      /nakama/nakama migrate up --database.address postgres:localdb@127.0.0.1:5432/nakama &&
      exec /nakama/nakama --name nakama1 --database.address postgres:localdb@127.0.0.1:5432/nakama --logger.level DEBUG --console.port 7351
      "
    network_mode: "host"
    restart: unless-stopped

volumes:
  pgdata: {}
